name: test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker containers
      run: |
        make build
        make run

    - name: Run tests
      run: /
        make test
